server:
  port: 5050
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth
          uri: http://localhost:9080/auth/
          predicates:
            - Path= /auth/**
            #==========================
        - id: mailbox
          uri: http://localhost:9070/mailbox/
          predicates:
            - Path= /mailbox/**
            #==========================

  application:
    name: gateway


  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway